name: 'Build, Pack & Publish'

on:
  push:
    branches: [ master ]

env:
  CI_REPOSITORY_URL: https://github.com/${{ github.repository }}
  CI_COMMIT_REF_NAME: ${{ github.ref }}
  CI_COMMIT_SHA: ${{ github.sha }}
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  
jobs:
  build:
    strategy:
      matrix: 
        project: [ 'RocketUI', 'RocketUI.Design', 'RocketUI.Design.Host' ]
        include:
          - project: RocketUI
            projectSrc: src/RocketUI/RocketUI.csproj

          - project: RocketUI.Design
            projectSrc: src/RocketUI.Design/RocketUI.Design.csproj

          - project: RocketUI.Design.Host
            projectSrc: src/RocketUI.Design.Host/RocketUI.Design.Host.csproj

    runs-on: ubuntu-latest
    steps:
    - name: Checkout  
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        
    - name: Build & Pack Projects
      shell: bash
      run: dotnet pack -o ./nuget -p:PackageVersion=1.0.${{ github.run_number }} --include-symbols --include-source ${{ matrix.projectSrc }}
    
    - name: Publish NuGet Packages
      shell: bash
      run: |
        for f in ./nuget/*.nupkg; do
          dotnet nuget push "$f" -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_KEY }} --skip-duplicate
        done
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.project }}
        path: ./nuget
    